### ISSUE TITLE
No PMP entry is configured, so the boot process will fail with illegal instruction

### ISSUE THREAD

**Issue by hobo0xcc** [o8vm/octox#1]
According to https://github.com/qemu/qemu/commit/d102f19a2085ac931cb998e6153b73248cca49f1, QEMU will raise an illegal instruction exception when it executes an mret instruction but no PMP entry is configured.
So the following code in `start` function fixes the bug (in my case).

```rust
    let pmpaddr0 = (!0_usize) >> 10;
    asm!("csrw pmpaddr0, {}", in(reg) pmpaddr0);
    let mut pmpcfg0 = 0_usize;
    pmpcfg0 |= 3 << 3;
    pmpcfg0 |= 1 << 2;
    pmpcfg0 |= 1 << 1;
    pmpcfg0 |= 1 << 0;
    asm!("csrw pmpcfg0, {}", in(reg) pmpcfg0);
```

Older version of QEMU doesn't check whether PMP entry is configured correctly.

**Comment by o8vm** [comment]
I did not know this. Thank you very much. I'll give it a try! 🥳

**Comment by o8vm** [comment]
This issue has probably been addressed in [this commit](https://github.com/o8vm/octox/commit/bf0843374e86745f9f5c2fff9053aef7fda44e57).
