### ISSUE TITLE
Please add a license.

### ISSUE THREAD

**Issue by ajh123** [o8vm/octox#13]
~~Adding a license will control what people can legally do with your code. Currently we are not legally allowed to install your software, even though the code is public on GitHub it doesn't mean we can use it. (see more: https://choosealicense.com/no-permission/) Currently you are legally liable for any issues that occur, this may become an issue in the future if no license is applied.~~

~~To add a license create a file called `LICENSE` inside the root of this repository and~~ paste the content of the license of your choice inside it (and modify placeholders if there are any). ~~To choose a license visit https://choosealicense.com.~~ (just saying it in the README is not enough because GitHub will mark this repository has not having a license)

~~In the Rust world it is common to have the MIT (found at https://choosealicense.com/licenses/mit/) and Apache 2.0 (https://choosealicense.com/licenses/apache-2.0/) licenses.~~ This means instead of having a signal `LICENSE` file, you would create two files one called `LICENSE-MIT` and the other `LICENSE-APACHE`.

**Comment by ajh123** [comment]
Oh, I've seen it in the bottom of the README - however you should still create the files so GitHub can label the repository as having these licenses.

**Comment by o8vm** [comment]
Thank you for informing me! I will proceed to add those files!

**Comment by ajh123** [comment]
Here is an example of what it will look like:

![image](https://github.com/o8vm/octox/assets/41990982/b79753c2-8a76-488f-ae94-7db38b226ef2)

**Comment by o8vm** [comment]
added! thanks!
