### ISSUE TITLE
dependency problem

### ISSUE THREAD

**Issue by wei-huan** [o8vm/octox#2]
: ~/WorkSpace/octox$ cargo run
   Compiling octox v0.1.0 (/home/weihuan/WorkSpace/octox)
error: failed to run custom build command for `octox v0.1.0 (/home/weihuan/WorkSpace/octox)`

Caused by:
  process didn't exit successfully: `/home/weihuan/WorkSpace/octox/target/debug/build/octox-8e3ec1183ade9570/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=/home/weihuan/WorkSpace/octox/src/mkfs

  --- stderr
     Compiling mkfs v0.1.0 (/home/weihuan/WorkSpace/octox/src/mkfs)
  error[E0432]: unresolved import `crate::bio`
   --> ../kernel/fs.rs:1:12
    |
  1 | use crate::bio::BCACHE;
    |            ^^^ could not find `bio` in the crate root

  error[E0432]: unresolved import `crate::log`
   --> ../kernel/fs.rs:2:12
    |
  2 | use crate::log::LOG;
    |            ^^^ could not find `log` in the crate root

  error[E0432]: unresolved import `crate::proc`
   --> ../kernel/fs.rs:4:12
    |
  4 | use crate::proc::{CopyInOut, CPUS};
    |            ^^^^ could not find `proc` in the crate root

  error[E0432]: unresolved import `crate::sleeplock`
   --> ../kernel/fs.rs:5:12
    |
  5 | use crate::sleeplock::{SleepLock, SleepLockGuard};
    |            ^^^^^^^^^ could not find `sleeplock` in the crate root

  error[E0432]: unresolved import `crate::spinlock`
   --> ../kernel/fs.rs:6:12
    |
  6 | use crate::spinlock::Mutex;
    |            ^^^^^^^^ could not find `spinlock` in the crate root

  error[E0432]: unresolved imports `crate::lazy`, `crate::vm`
    --> ../kernel/fs.rs:9:5
     |
  9  |     lazy::{SyncLazy, SyncOnceCell},
     |     ^^^^
     |     |
     |     unresolved import
     |     help: a similar path exists: `core::lazy`
  10 |     vm::VirtAddr,
     |     ^^ could not find `vm` in the crate root

  error[E0425]: cannot find value `SB` in this scope
     --> ../kernel/fs.rs:107:5
      |
  107 |     SB.set(SuperBlock::read(dev)).unwrap();
      |     ^^ not found in this scope

  error[E0425]: cannot find value `SB` in this scope
     --> ../kernel/fs.rs:108:14
      |
  108 |     let sb = SB.get().unwrap();
      |              ^^ not found in this scope

  error[E0425]: cannot find value `SB` in this scope
     --> ../kernel/fs.rs:124:14
      |
  124 |     let sb = SB.get().unwrap();
      |              ^^ not found in this scope

  error[E0425]: cannot find value `SB` in this scope
     --> ../kernel/fs.rs:146:14
      |
  146 |     let sb = SB.get().unwrap();
      |              ^^ not found in this scope

  error[E0425]: cannot find value `SB` in this scope
     --> ../kernel/fs.rs:267:18
      |
  267 |         let sb = SB.get().unwrap();
      |                  ^^ not found in this scope

  error[E0425]: cannot find value `SB` in this scope
     --> ../kernel/fs.rs:534:18
      |
  534 |         let sb = SB.get().unwrap();
      |                  ^^ not found in this scope

  error[E0425]: cannot find value `SB` in this scope
     --> ../kernel/fs.rs:594:18
      |
  594 |         let sb = SB.get().unwrap();
      |                  ^^ not found in this scope

  Some errors have detailed explanations: E0425, E0432.
  For more information about an error, try `rustc --explain E0425`.
  error: could not compile `mkfs` due to 13 previous errors
  thread 'main' panicked at 'Subcrate build failed!', build.rs:61:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by o8vm** [comment]
Thank you!! This issue has been fixed in this commit: [5af33c0](https://github.com/o8vm/octox/commit/5af33c0b31e093b63202c7225f347a5a58075fc6)

**Comment by o8vm** [comment]
If you would like to star⭐ this project, that would encourage me to develop!

**Comment by wei-huan** [comment]
Sure. No problem. Your project is awesome. Have you ever heard opensbi? It's a standard bootloader for risc-v architecture, you can have a try if you like.

**Comment by o8vm** [comment]
Thanks very much! Yes, I've known opensbi. If I complete the implementation, I try to implement it! 🥳
